version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 80:3000

  backend:
    depends_on:
      - db1
      - db2
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB1_URL: mongodb://db1/vidly1
      DB2_URL: mongodb://db2/vidly2
    command: ./docker-entrypoint.sh

  db1:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly1:/data/db

  db2:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - vidly2:/data/db

volumes:
  vidly1:
  vidly2:
